name: Publish Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: alexeylesin/pterodactyl-core
      
      - name: Build and push Docker image - Java 11
        uses: docker/build-push-action@v2
        with:
          file: java-11/Dockerfile
          context: ./java-11
          push: true
          repository: alexeylesin/pterodactyl-core
          tags: java-11

      - name: Build and push Docker image - Java 17
        uses: docker/build-push-action@v2
        with:
          file: java-17/Dockerfile
          context: ./java-17
          push: true
          repository: alexeylesin/pterodactyl-core
          tags: java-17
